#file: noinspection undefined
server:
  port: 9999
  servlet:
    context-path: /api/v1


spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/supermarket_management}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:8082}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          charSet: utf8mb4
          useUnicode: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

com:
  anonymous:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      valid-duration: 86400
      refreshable-duration: 864000
    origin-client-1: http://localhost:4200
    username-admin: ${ADMIN_USERNAME:admin1234}
    admin-password: ${ADMIN_PASSWORD:Admin@123456}
    employee-default-password: ${EMPLOYEE_DEFAULT_PASSWORD:12345678}

